apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: registry.orientsoft.cn/other/sample:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: sample
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30999
      name: sample-port
  type: NodePort
